version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: barberDB
    environment:
      POSTGRES_DB: barberDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always