spring:
  application:
    name: BarberSystem

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/barberDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

barbersystem:
  security:
    secret: "palavra-secreta"



